import { OrderDetail } from "../types";

export const initialData: OrderDetail = {
  $id: "",
  name: "",
  description: "",
  image: "",
  price: "",
  rating: "",
  foodType: "",
  isFavorite: false,
  tmpId: "",
  quantity: 0,
  size: "",
  address: "",
  bought: 0,
  subtotal: 0,
  user: "",
  product: {
    $id: "",
    name: "",
    description: "",
    image: "",
    price: "",
    rating: "",
    foodType: "",
    isFavorite: false,
    bought: 0,
  },
};
